name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }} # secret 名
          PUBLISH_REPOSITORY: xjtuicpc/board
          BRANCH: gh-pages 
          PUBLISH_DIR: ./public 
