name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: hexo generate

    - name: Deploy to GitHub Pages
      run: hexo deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

